language: python
python:
  - "3.7"
before_install:
  - sudo apt-get install -y freeglut3-dev
services:
  - xvfb
install:
  - pip install pipenv
  - pipenv install
  - pip install pytest pytest-cov coveralls shapely
script:
  - pytest --cov --ignore=/home #=.
after_success:
  - coveralls